### ISSUE TITLE
functional_tensor not found 

### ISSUE THREAD

**Issue by sdlpkxd** [XPixelGroup/BasicSR#533]
when I run training code, it reports ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

my environment:
Mac M1 chip
python 3.9
torch 1.10.2
torchvision 0.2.2

Should torchvision.transforms.functional_tensor be torchvision.transforms.functional ?
Need help

**Comment by ssube** [comment]
I am also encountering this after upgrading to PyTorch 2.x. Based on checking a few venvs, it looks like ` torchvision.transforms.functional_tensor` was available up through 0.14.1 but is not present in 0.15.0 or better.

**Comment by kamyker** [comment]
Works for me but i get:
```
The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional. 
```

**Comment by gordon0907** [comment]
I'm also having this warning. As I searched in the repo, `torchvision.transforms.functional_tensor` is only called in "basicsr/data/degradations.py". Replacing the import line `torchvision.transforms.functional_tensor` in this file, with `torchvision.transforms.functional` should solve the warning problem.

Environment:
macOS 13.4 (Apple M1 Max)
Python 3.10.11
torch 2.0.1
torchvision 0.15.2

**Comment by shun-lin** [comment]
Looks like this package is not updated anymore, to patch the issue in your python program you may add those lines

```
from torchvision.transforms import functional
import sys

sys.modules["torchvision.transforms.functional_tensor"] = functional
```

which will redirect `torchvision.transforms.functional_tensor` to `torchvision.transforms.functional` so the broken import will now work again w/ latest torchvision.

**Comment by sdlpkxd** [comment]
Yea, using torchvision.transforms.functional instread of torchvision.transforms.functional_tensor is recommended for the latest torchvision

**Comment by bedbad** [comment]
Why do users have to patch those every time?
This is definetely not solved. If the package is not updated anymore - change a maintaner or release managed fork
The package is used.

**Comment by lightandshadow68** [comment]
This is not a solution when BasicSR is used as a dependency in a library. Nor can I patch a file as part of an automated test suite.

**Comment by lightandshadow68** [comment]
> I am also encountering this after upgrading to PyTorch 2.x. Based on checking a few venvs, it looks like ` torchvision.transforms.functional_tensor` was available up through 0.14.1 but is not present in 0.15.0 or better.

It has been deprecated for some time now, and was eventually removed.

**Comment by 14790897** [comment]
I released a fixed version to address this issue. Use `pip install basicsr-fixed` instead of `pip install basicsr`.
